version: '3'

services:
  backend:
    build: backend/
    ports: 
      - 8000:8000
    networks:
      - deploy_network
    container_name: backend

  frontend:
    build: frontend/
    depends_on:
      - backend
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: frontend

networks:
  deploy_network:
    driver: bridge
